version: '3.8'

services:
  discord-bot:
    container_name: discord-weather-bot
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    working_dir: /app
    env_file:
      - .env
    volumes:
      - .:/app
    command: node bot.js
